/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

module.exports = {
  design: [
    {
      type: 'autogenerated',
      dirName: 'design',
    }, 
      ],
  develop: [
    {
      type: 'autogenerated',
      dirName: 'develop',
    },    
    ],
  po: [
    {
      type: 'autogenerated',
      dirName: 'po',
    },  
  ],
  support: [
    {
      type: 'autogenerated',
      dirName: 'support',
    },  
  ]
};
